---
legislative_types:
  - name: Bill
    abbr: S.
    description: A bill authorizes the spending of money or change in the law. Requires the approval of the President.
  - name: Resolution
    abbr: S.Res.
    description: A resolution takes an action within the chamber such as a rule change or expresses an non-binding opinion. Does not require Presidental approval.
  - name: Joint Resolution
    abbr: S.J.Res.
    description: A Joint Resolution is used to amend the Constitution, requiring a 2/3rds majority in both chambers and 3/4ths of the States.
