plugins: 
- fullscreen
- autosave
menubar: 'file edit insert view format table tools help'
toolbar:
  - styleselect | bold italic underline | undo redo | fullscreen | restoredraft
  - image | link

browser_spellcheck: true
license_key: 'gpl'