plugins: 
- fullscreen
- autosave
- lists
menubar: 'file edit insert view format table tools help'
toolbar:
  - styleselect |  undo redo | blocks | bold italic underline | numlist bullist | restoredraft | fullscreen
  - image | link 
browser_spellcheck: true
license_key: 'gpl'